name: .NET Build and Test

# Uruchamianie pipeline'a na push lub pull request do gałęzi main
on:
  push:
    branches:
      - main
      - restfulframework-allure
  pull_request:
    branches:
      - main
      - restfulframework-allure

jobs:
  build:
    runs-on: ubuntu-latest  # Można też wybrać windows-latest, ale ubuntu jest szybsze

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Zmieniaj na odpowiednią wersję .NET, np. '6.x' jeśli używasz .NET 6

    - name: Restore dependencies
      run: dotnet restore restfulbookers/restfulbookers/restfulbookers.csproj

    - name: Build the solution
      run: dotnet build restfulbookers/restfulbookers/restfulbookers.csproj --configuration Release --no-restore

    - name: Run tests and generate NUnit XML results
      run: dotnet test restfulbookers/restfulbookers/restfulbookers.csproj --logger "nunit;LogFilePath=restfulbookers/restfulbookers/bin/Debug/net8.0/allure-results/TestResults.xml"
        
    # Instalacja Allure za pomocą repozytorium Maven Central
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.zip
        unzip allure-commandline-2.30.0.zip -d /opt/allure
        sudo ln -s /opt/allure/allure-2.30.0/bin/allure /usr/bin/allure
        
    # Generate Allure Report from allure-results directory
    - name: Generate Allure Report
      run: allure generate restfulbookers/restfulbookers/bin/Debug/net8.0/allure-results --clean -o restfulbookers/restfulbookers/bin/Debug/net8.0/allure-report

    - name: List files in allure-results directory
      run: ls -la restfulbookers/restfulbookers/bin/Debug/net8.0/allure-results

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: restfulbookers/restfulbookers/bin/Debug/net8.0/allure-report
