name: .NET Build and Test

# Uruchamianie pipeline'a na push lub pull request do gałęzi main
on:
  push:
    branches:
      - main
      - restfulframework-allure
  pull_request:
    branches:
      - main
      - restfulframework-allure


env:
  DOTNET_VERSION: '8.x'
  PROJECT_PATH: 'restfulbookers/restfulbookers'
  REPO_PATH_FOR_ALLURE: 'bin/Debug/net8.0'
  
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/restfulbookers.csproj

    - name: Build the solution
      run: dotnet build ${{ env.PROJECT_PATH }}/restfulbookers.csproj --configuration Release --no-restore

  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run tests and generate NUnit XML results
      run: dotnet test ${{ env.PROJECT_PATH }}/restfulbookers.csproj --logger "nunit;LogFilePath=bin/Debug/net8.0/allure-results/TestResults.xml" --verbosity detailed

  allure-report:
    runs-on: ubuntu-latest
    steps:
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.zip
        unzip allure-commandline-2.30.0.zip -d /opt/allure
        sudo ln -s /opt/allure/allure-2.30.0/bin/allure /usr/bin/allure
        
    - name: Generate Allure Report
      run: allure generate ${{ env.PROJECT_PATH }}/${{ env.REPO_PATH_FOR_ALLURE }}/allure-results --clean -o ${{ env.PROJECT_PATH }}/${{ env.REPO_PATH_FOR_ALLURE }}/allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.PROJECT_PATH }}/${{ env.REPO_PATH_FOR_ALLURE }}/allure-report
